### ISSUE TITLE
Tried every possible environment but label problem persists.

### ISSUE THREAD

**Issue by berkekavak** [ncbi/BioRED#2]
```
Traceback (most recent call last):
  File "src/run_biored_exp.py", line 795, in <module>
    main()
  File "src/run_biored_exp.py", line 624, in main
    cache_dir  = model_args.cache_dir,
  File "/home/berkekavak/miniconda3/envs/species/lib/python3.6/site-packages/transformers/models/auto/auto_factory.py", line 446, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "/home/berkekavak/miniconda3/envs/species/lib/python3.6/site-packages/transformers/modeling_tf_utils.py", line 1796, in from_pretrained
    return load_pytorch_checkpoint_in_tf2_model(model, resolved_archive_file, allow_missing_keys=True)
  File "/home/berkekavak/miniconda3/envs/species/lib/python3.6/site-packages/transformers/modeling_tf_pytorch_utils.py", line 121, in load_pytorch_checkpoint_in_tf2_model
    pt_state_dict = torch.load(pt_path, map_location="cpu")
  File "/home/berkekavak/miniconda3/envs/species/lib/python3.6/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/berkekavak/miniconda3/envs/species/lib/python3.6/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
cp: cannot stat 'out_model_biored_novelty/test_results.tsv': No such file or directory
Traceback (most recent call last):
  File "src/utils/run_biored_eval.py", line 923, in <module>
    labels                   = labels)
  File "src/utils/run_biored_eval.py", line 884, in run_test_eval
    labels                   = labels)
  File "src/utils/run_biored_eval.py", line 189, in dump_pred_2_pubtator_file
    pmids = sorted(list(pmid_2_rel_pairs_dict.keys()), reverse=True)
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by ptlai** [comment]
#1

**Comment by ptlai** [comment]
I have recently updated our source code, including the package versions. You can find them in the [biored_re_source_code.tar](https://ftp.ncbi.nlm.nih.gov/pub/lu/BioRED/biored_re_source_code.tar)
